server:
  port: 8081
spring:
  application:
    name: bitoasis-assignment
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    password: sa
    username: sa
    platform: h2
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    time:
      ticker: 5
coin:
  url:
    alternative-me: https://api.alternative.me/v2